project:
  type: website
  output-dir: docs

website:
  title: "Myweb"
  navbar:
    left:
    - About Me.qmd
    - Projects.qmd
    - Work Experience.qmd
    - Skills.qmd
    - Education.qmd
    - Certificates and Achievements.qmd
    - Social Media.qmd
    - Contact.qmd

format:
  html:
    theme: cosmo