---
title: "Certificates and Achievements"
editor: visual
---

-   **Combined Annual Training Camp - II:**

    -   Attended the camp held at Agricultural Market Yard, Nuzyvid, contributing to the 19 Andhra BN NCC.

-   **Public Health Contributor \| Unit of Good Samaritan Blood Centre:**

    -   Devoted volunteer and regular blood donor, actively promoting community health and well-being.

-   **Regional and State Level Sports:**

    -   Represented my school in Volleyball at both regional and state-level sports meets, fostering team spirit.

-   **Member of International Programs and Services**

    -   Active member, contributing to collaboration and support for individuals worldwide.

-   **Understanding Weather & Climate \| Intra-Regional Level:**

    -   Participated in the event held at Kendriya Vidyalaya No.2, Uppal, Hyderabad & Air Force Station, Begumpet - Hyderabad.

[Extra Curricular Files](https://chat.openai.com/c/drive.google.com/drive/folders/1C39k_Tc5e2uJtsYdeXFv8lWXqyomX5TY?usp=sharing)
