---
title: "Extracurricular"
editor: visual
---

-   **Combined Annual Training Camp - II:**

    -   Attended the camp held at Agricultural Market Yard, Nuzyvid, contributing to the 19 Andhra BN NCC.

        [Certificate here](https://drive.google.com/file/d/1-MkfAxoXGASQd1nGFFVhpOmgjy0bVaJC/view?usp=sharing)

-   **Public Health Contributor \| Unit of Good Samaritan Blood Centre:**

    -   Devoted volunteer and regular blood donor, actively promoting community health and well-being.

        [Certificate here](https://drive.google.com/file/d/1c8RNijt0woszZsKifZ1exhIYbxrKGn7S/view?usp=sharing)

-   **Regional and State Level Sports:**

    -   Represented my school in Volleyball at both regional and state-level sports meets, fostering team spirit.

        [Certificate here](https://drive.google.com/drive/folders/1SKPCai4Dd2hhTj4m8rFWIkliOFSqLK50?usp=sharing)

-   **Understanding Weather & Climate \| Intra-Regional Level:**

    -   Participated in the event held at Kendriya Vidyalaya No.2, Uppal, Hyderabad & Air Force Station, Begumpet - Hyderabad.

        [Certificate here](https://drive.google.com/drive/folders/14ghlsGzhxCD5GAYkJWg9IZ6bTdxSoUmv?usp=sharing)

```{=html}
<!-- -->
```
-   **Musical Composition Contributions:**

    -   Possessing strong knowledge and skills in music.

        [Certificate here](https://drive.google.com/drive/folders/1g4iwyARAJ1_oQBgn2as_4CC1PXN8VC9v?usp=sharing)

-   **Member of International Programs and Services:**

    -   Active member, contributing to collaboration and support for individuals worldwide.
